# Generated by Django 3.2.12 on 2023-01-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
